version: 0.0
os: linux
files:
  - source: /aws
    destination: /usr/local/codedeployresources
hooks:
  BeforeInstall:
    - location: aws/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application_start.sh
      timeout: 300
      runas: root