version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: valhub
      POSTGRES_PASSWORD: valhub
      POSTGRES_USER: valhub
    ports:
      - "5432:5432"
    volumes:
      - valhub:/data/db

  api:
    build:
      context: ./valhub
      args:
        djangosk: ${djangosk} 
    env_file:
      - .env
    environment:
      PGDATABASE: valhub
      PGUSER: valhub
      PGHOST: db
      PG_DATABASE_URI: "postgresql://valhub:valhub@db/valhub"
      DJANGO_SECRET_KEY: ${djangosk}
    ports:
      - "8005:8005"
    depends_on:
      - db

  s3:
    build: ./s3Emulator
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - api

  react-client:
    stdin_open: true
    build: ./frontend
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./frontend:/opt/app:delegated
    ports:
      - "3000:3000"
    depends_on:
      - api
      - s3
      
  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
    environment:
      - "ELASTICMQ_OPTS=-Dconfig.file=/opt/docker/custom.conf"
    volumes:
      - ./custom.conf:/opt/docker/custom.conf
    depends_on:
      - api

volumes:
 valhub:
