# Generated by Django 3.2.16 on 2023-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValidationTests",
            fields=[
                (
                    "category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(max_length=128)),
                ("performance_metrics", models.JSONField()),
                ("function_name", models.CharField(max_length=128)),
            ],
        ),
    ]
