# Generated by Django 3.2.16 on 2024-08-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_alter_submission_python_version"),
        ("error_report", "0002_auto_20240403_0814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorreport",
            name="error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="errorreport",
            name="error_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="errorreport",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_report",
                to="submissions.submission",
            ),
        ),
    ]
