# Generated by Django 5.1.1 on 2024-09-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_report', '0003_auto_20240827_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='file_errors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
