# Generated by Django 4.1.2 on 2022-12-02 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=32, null=True)),
                ('lastName', models.CharField(max_length=32, null=True)),
                ('githubLink', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
