# Generated by Django 4.1.2 on 2022-11-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, null=True)),
                ('githubLink', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
