# Generated by Django 3.2.16 on 2024-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20240524_2326"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="webLinks",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
