# Generated by Django 3.2.16 on 2024-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_weblinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="webLinks",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
