# Generated by Django 3.2.16 on 2024-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20240822_2307"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profileImage",
            field=models.CharField(default="ducky.jpg", max_length=64),
        ),
    ]
