FROM postgres:15-alpine as base

# Only used for local development. Emulates a backend database. Env is not actually user here. 

ENV POSTGRES_PASSWORD=valhub
ENV user=valhub
ENV PORT 5432
EXPOSE 5432
