FROM postgres:15-alpine as base

# Only used for local development. Emulates a backend database. 

ENV POSTGRES_PASSWORD=valhub
ENV POSTGRES_DB=valhub
ENV POSTGRES_USER=valhub
ENV PORT 5432
EXPOSE 5432
