# Generated by Django 3.2.16 on 2023-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetadata',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('azimuth', models.FloatField()),
                ('tilt', models.FloatField()),
                ('elevation', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tracking', models.BooleanField()),
                ('dc_capacity', models.FloatField()),
            ],
        ),
    ]
