# Generated by Django 3.2.16 on 2024-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmetadata",
            name="dc_capacity",
            field=models.FloatField(default=0.0),
        ),
    ]
