# Generated by Django 3.2.16 on 2023-11-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system_metadata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=256)),
                ("timezone", models.CharField(max_length=128)),
                ("data_sampling_frequency", models.PositiveIntegerField()),
                ("issue", models.CharField(max_length=256)),
                ("subissue", models.CharField(max_length=256)),
                (
                    "system_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_metadata.systemmetadata",
                    ),
                ),
            ],
        ),
    ]
