# Generated by Django 5.1.6 on 2025-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="file_hash",
            field=models.CharField(default="", max_length=256),
        ),
    ]
