# Generated by Django 5.1.6 on 2025-02-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_metadata", "0002_filemetadata_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="is_real",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="file_hash",
            field=models.CharField(max_length=256),
        ),
    ]
