# Generated by Django 5.1.7 on 2025-03-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_metadata",
            "0003_filemetadata_is_real_alter_filemetadata_file_hash",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="filemetadata",
            old_name="is_real",
            new_name="include_on_leaderboard",
        ),
    ]
