# Generated by Django 3.2.16 on 2023-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "analysis_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "analysis_name",
                    models.CharField(default="analysis", max_length=100),
                ),
                (
                    "max_concurrent_submission_evaluation",
                    models.IntegerField(default=100),
                ),
            ],
        ),
    ]
