# Generated by Django 3.2.16 on 2024-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="max_concurrent_submission_evaluation",
        ),
        migrations.AddField(
            model_name="analysis",
            name="result",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
