# Generated by Django 5.1.4 on 2025-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0005_analysis_total_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="version",
            field=models.CharField(default="1.0.0", max_length=100),
        ),
    ]
