# Generated by Django 5.1.6 on 2025-02-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0006_analysis_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="hash",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="version",
            field=models.CharField(default="1.0", max_length=100),
        ),
    ]
