# Generated by Django 3.2.16 on 2024-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="data_requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
