# Generated by Django 3.2.16 on 2024-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_alter_submission_data_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="alt_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
