# Generated by Django 3.2.16 on 2024-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_submission_alt_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
