# Generated by Django 3.2.16 on 2024-07-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_submission_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="python_version",
            field=models.FloatField(default=3.11),
        ),
        migrations.AddField(
            model_name="submission",
            name="worker_version",
            field=models.FloatField(default=1.0),
        ),
    ]
