# Generated by Django 3.2.16 on 2024-07-18 00:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_auto_20240718_0015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="python_version",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.11"), max_digits=4
            ),
        ),
    ]
