# Generated by Django 3.2.16 on 2024-07-30 17:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_alter_submission_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="mae",
        ),
        migrations.AlterField(
            model_name="submission",
            name="data_requirements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
