# Generated by Django 3.2.16 on 2024-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_auto_20240730_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="python_version",
            field=models.CharField(default="3.11", max_length=10),
        ),
    ]
