# Generated by Django 5.1 on 2024-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submission_python_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='current_file_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
