# Generated by Django 5.1 on 2024-08-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0010_submission_current_file_count_submission_progress_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="progress",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
