# Generated by Django 5.1.4 on 2025-01-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0012_submission_avg_file_exec_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="analysis_version",
            field=models.CharField(default="1.0.0", max_length=100),
        ),
        migrations.AlterField(
            model_name="submission",
            name="worker_version",
            field=models.CharField(default="1.0.0", max_length=100),
        ),
    ]
