# Generated by Django 5.1.6 on 2025-02-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0013_submission_analysis_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="analysis_version",
            field=models.CharField(default="1.0", max_length=100),
        ),
        migrations.AlterField(
            model_name="submission",
            name="worker_version",
            field=models.CharField(default="1.0", max_length=100),
        ),
    ]
