name: Build and Test

on:
  push:
  workflow_dispatch:

env:
  applicationfolder: valhub
  AWS_REGION: us-west-2
  S3BUCKET: pv-validation-hub-bucket
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  build-api:
    name: Build and Test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./valhub"
          version: "24.2.0"

      - name: build
        run: |
          cd valhub
          export DOCKER_BUILDKIT=1
          docker build --build-arg admin_username="placeholder" --build-arg admin_password="placeholder" --build-arg djangosk="${{ env.DJANGO_SECRET_KEY }}" -t pv/val:tag -f Dockerfile .

  build-worker:
    name: Build and Test Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./workers"
          version: "24.2.0"

      - name: build
        run: |
          cd workers
          export DOCKER_BUILDKIT=1
          docker build -t pv/val:tag -f Dockerfile .
