name: Build and Test

on:
  push:
  workflow_dispatch:

env:
  applicationfolder: valhub
  AWS_REGION: us-west-2
  S3BUCKET: pv-validation-hub-bucket
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}


jobs:
  build-fe:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: install dependencies and build
        run: |
          cd frontend
          cp .env.example .env
          npm install
          npm run build

      - name: run tests
        run: |
          cd frontend
          npm run test

  build-api:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: build
        run: |
          cd valhub
          export DOCKER_BUILDKIT=1
          docker build --build-arg admin_username="placeholder" --build-arg admin_password="placeholder" --build-arg djangosk="${{ env.DJANGO_SECRET_KEY }}" -t pv/val:tag -f Dockerfile .

  build-worker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: build
        run: |
          cd workers
          export DOCKER_BUILDKIT=1
          docker build -t pv/val:tag -f Dockerfile .
