name: Build and Test

on:
    push:
    workflow_dispatch:

env:
    DJANGOSK: ${{ secrets.DJANGOSK }}

jobs:
    build-api:
        name: Build and Test API
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout Repository

            - uses: psf/black@stable
              with:
                  options: '--check --verbose'
                  src: './valhub'
                  version: '25.1.0'

            - name: build
              run: |
                  cd valhub
                  export DOCKER_BUILDKIT=1
                  docker build --build-arg admin_username="placeholder" --build-arg admin_password="placeholder" --build-arg djangosk="${{ env.DJANGOSK }}" -t pv/val:tag -f Dockerfile .

    build-worker:
        name: Build and Test Worker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout Repository

            - uses: psf/black@stable
              with:
                  options: '--check --verbose'
                  src: './workers'
                  version: '25.1.0'

            - name: build
              run: |
                  cd workers
                  export DOCKER_BUILDKIT=1
                  docker build -t pv/val:tag -f Dockerfile .
