name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  applicationfolder: valhub
  AWS_REGION: us-east-2
  S3BUCKET: validationhubdjango-webappdeploymentbucket-1fhm2xs8nqcj0


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: chmod
        run: chmod -R +x ./.github

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run Tests
        run: |
          python3 manage.py test 
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Upload Artifact to s3
        run: aws s3 cp deploy.zip s3://${{ env.S3BUCKET }}/
      
      - run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures