name: Build and Deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  applicationfolder: valhub
  AWS_REGION: us-east-2
  S3BUCKET: pv-insight-pipeline-bucket
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    environment: test
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: chmod
        run: chmod -R +x ./.github

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run Tests
        working-directory: ${{ env.applicationfolder }}
        run: |
          python3 manage.py test 
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Upload Artifact to s3
        run: aws s3 cp deploy.zip s3://${{ env.S3BUCKET }}/
      
      - run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name pv-validation-hub-dev --deployment-group-name pvvalhub --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures