name: Example publish release
on:
  push:
    branches:
      - main
jobs:
    job1:
        runs-on: windows-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3

          - name: Here's a helpful link
            run: echo "https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions"

          - name: The other workflow shouldn't run
            run: echo "That is the power of setting workflow events."

          - name: Even if it did...
            run: echo "It should fail as the environments it uses don't exist.... yet"