name: Example publish release
on:
  release:
    types: [published]
jobs:
    job1:
        runs-on: ubuntu-latest
        environment: testing
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3

          - name: Install Twine
            run: sudo pip install twine

    job2:
        runs-on: macos-latest
# sets default shell to remove need for source to run the conda shell
        defaults:
          run:
            shell: bash -l {0}
        environment: example
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3

          - name: Install Twine
            run: sudo pip install twine

          - name: This runs multiple commands
            run: |
              echo "Line 1"
              echo "Line 2"