name: Example test deploy
on:
  pull_request:

jobs:
    job1:
        runs-on: ubuntu-latest
        environment: easy-deploy
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3
          
          
